---
title: "Arima for loop"
output: html_document
---

############################
## 2019 all months ARIMA ##
############################
```{r}
library(forecast)
library(readxl)
EnergyDataset <- read_excel("/Users/nicklasschmidt/Downloads/Master thesis/Dataset/EnergyDataset.xlsx", 
    col_types = c("date", "numeric", "numeric", 
        "numeric", "numeric", "numeric", 
        "numeric"))

startYear = 2017
Year = 2019
Month = c("February", "July", "September", "December")
MonthNumber = c(32, 182, 244, 335)

for(MonthVariables in 1:4){
naivedata=subset(EnergyDataset[1:2623,1:2])
# First we convert dataset into a time series object
naivedec = ts(EnergyDataset[,2:2], start = c(2015,1), frequency = 365 )

#Subsetting train and test data using window()function 
month2019train = window(naivedec, start = c(startYear, MonthNumber[MonthVariables]), end = c(Year, MonthNumber[MonthVariables]))
month2019test = window(naivedec, start = c(Year, MonthNumber[MonthVariables]))

#Models estimating the best pdq.
#arima2019=auto.arima(month2019train, trace=TRUE, approximation = T,allowdrift = T,allowmean = T) 
arima2019=Arima(month2019train, order = c(7, 1, 2))

#Forecasting for 1-28 days 
model1dec2019=forecast(arima2019,h=1, level=c(95))
model7dec2019=forecast(arima2019,h=7, level=c(95))
model14dec2019=forecast(arima2019,h=14, level=c(95))
model21dec2019=forecast(arima2019,h=21, level=c(95))
model28dec2019=forecast(arima2019,h=28, level=c(95))

# Accuracy TABLE
decna1=forecast::accuracy(model1dec2019, month2019test, d=1, D=0)[2,1:6]
decna7=forecast::accuracy(model7dec2019, month2019test, d=1, D=0)[2,1:6]
decna14=forecast::accuracy(model14dec2019, month2019test, d=1, D=0)[2,1:6]
decna21=forecast::accuracy(model21dec2019, month2019test, d=1, D=0)[2,1:6]
decna28=forecast::accuracy(model28dec2019, month2019test, d=1, D=0)[2,1:6]

accuracytable = rbind(decna1,decna7,decna14,decna21,decna28)
#plot table
naivetable = cbind(Month[MonthVariables],accuracytable)
rownames(naivetable) = c("Point","7 days","14 days","21 days","28 days")

naivetsplot = window(naivedec, start = c(Year, 1),end = c(Year + 1,1))
prettyplot = autoplot(naivetsplot, xlab = "Year", ylab = "Electricity price in DK1 area", main="Vector AR plot, h=1,7,14,21,28")+autolayer(model28dec2019, series = "28 Days", PI = FALSE, size = 1)+autolayer(model21dec2019, series = "21 Days", PI = FALSE, size = 1)+autolayer(model14dec2019, series = "14 Days", PI = FALSE, size = 1)+autolayer(model7dec2019, series = "7 Days", PI = FALSE, size = 1)+autolayer(model1dec2019, series = "Days point", PI = FALSE, size = 1)
assign(paste0("prettyplot",MonthVariables),prettyplot)

if (MonthVariables == 1) {FebruaryTable = naivetable}
if (MonthVariables == 2) {JulyTable = naivetable}
if (MonthVariables == 3) {SeptemberTable = naivetable}
if (MonthVariables == 4) {DecemberTable = naivetable}
}
#subset DK1 
FebruaryTable[,c(3,4,7)]
JulyTable[,c(3,4,7)]
SeptemberTable[,c(3,4,7)]
DecemberTable[,c(3,4,7)]

RMSEtable = cbind(as.numeric(FebruaryTable[,3]),as.numeric(JulyTable[,3]),as.numeric(SeptemberTable[,3]),as.numeric(DecemberTable[,3]))
rownames(RMSEtable) = c("Point","7 days","14 days","21 days","28 days")
colnames(RMSEtable) = c("February","July","September","December")
AverageRMSEtable = rowMeans(RMSEtable)
AverageRMSEtable

MAEtable = cbind(as.numeric(FebruaryTable[,4]),as.numeric(JulyTable[,4]),as.numeric(SeptemberTable[,4]),as.numeric(DecemberTable[,4]))
rownames(MAEtable) = c("Point","7 days","14 days","21 days","28 days")
colnames(MAEtable) = c("February","July","September","December")
AverageMAEtable = rowMeans(MAEtable)
AverageMAEtable

MASEtable = cbind(as.numeric(FebruaryTable[,7]),as.numeric(JulyTable[,7]),as.numeric(SeptemberTable[,7]),as.numeric(DecemberTable[,7]))
rownames(MASEtable) = c("Point","7 days","14 days","21 days","28 days")
colnames(MASEtable) = c("February","July","September","December")
AverageMASEtable = rowMeans(MASEtable)
AverageMASEtable

prettyplot1
prettyplot2
prettyplot3
prettyplot4
```

############################
## 2021 all months ARIMA ##
############################
```{r}
library(forecast)
library(readxl)
EnergyDataset <- read_excel("/Users/nicklasschmidt/Downloads/Master thesis/Dataset/EnergyDataset.xlsx", 
    col_types = c("date", "numeric", "numeric", 
        "numeric", "numeric", "numeric", 
        "numeric"))
# 
startYear = 2019
Year = 2021
Month = c("February", "July", "September", "December")
MonthNumber = c(32, 182, 244, 335)

for(MonthVariables in 1:4){
naivedata=subset(EnergyDataset[1:2623,1:2])
# First we convert dataset into a time series object
naivedec = ts(EnergyDataset[,2:2], start = c(2015,1), frequency = 365 )

#Subsetting train and test data using window()function 
month2019train = window(naivedec, start = c(startYear, MonthNumber[MonthVariables]),end = c(Year, MonthNumber[MonthVariables]))
month2019test = window(naivedec, start = c(Year, MonthNumber[MonthVariables]))

#Models estimating the best pdq.
arima2019=Arima(month2019train, order = c(7, 1, 2))

#Forecasting for 1-28 days 
model1dec2019=forecast(arima2019,h=1, level=c(99.5))
model7dec2019=forecast(arima2019,h=7, level=c(99.5))
model14dec2019=forecast(arima2019,h=14, level=c(99.5))
model21dec2019=forecast(arima2019,h=21, level=c(99.5))
model28dec2019=forecast(arima2019,h=28, level=c(99.5))

# Accuracy TABLE
decna1=forecast::accuracy(model1dec2019, month2019test, d=1, D=0)[2,1:6]
decna7=forecast::accuracy(model7dec2019, month2019test, d=1, D=0)[2,1:6]
decna14=forecast::accuracy(model14dec2019, month2019test, d=1, D=0)[2,1:6]
decna21=forecast::accuracy(model21dec2019, month2019test, d=1, D=0)[2,1:6]
decna28=forecast::accuracy(model28dec2019, month2019test, d=1, D=0)[2,1:6]

accuracytable = rbind(decna1,decna7,decna14,decna21,decna28)
#plot table
naivetable = cbind(Month[MonthVariables],accuracytable)
rownames(naivetable) = c("Point","7 days","14 days","21 days","28 days")

naivetsplot = window(naivedec, start = c(Year, 1),end = c(Year + 1,1))
prettyplot = autoplot(naivetsplot, xlab = "Year", ylab = "Electricity price in DK1 area", main="Vector AR plot, h=1,7,14,21,28")+autolayer(model28dec2019, series = "28 Days", PI = FALSE, size = 1)+autolayer(model21dec2019, series = "21 Days", PI = FALSE, size = 1)+autolayer(model14dec2019, series = "14 Days", PI = FALSE, size = 1)+autolayer(model7dec2019, series = "7 Days", PI = FALSE, size = 1)+autolayer(model1dec2019, series = "Days point", PI = FALSE, size = 1)
assign(paste0("prettyplot",MonthVariables),prettyplot)

if (MonthVariables == 1) {FebruaryTable = naivetable}
if (MonthVariables == 2) {JulyTable = naivetable}
if (MonthVariables == 3) {SeptemberTable = naivetable}
if (MonthVariables == 4) {DecemberTable = naivetable}
}
#subset DK1 
FebruaryTable[,c(3,4,7)]
JulyTable[,c(3,4,7)]
SeptemberTable[,c(3,4,7)]
DecemberTable[,c(3,4,7)]

RMSEtable = cbind(as.numeric(FebruaryTable[,3]),as.numeric(JulyTable[,3]),as.numeric(SeptemberTable[,3]),as.numeric(DecemberTable[,3]))
rownames(RMSEtable) = c("Point","7 days","14 days","21 days","28 days")
colnames(RMSEtable) = c("February","July","September","December")
AverageRMSEtable = rowMeans(RMSEtable)
AverageRMSEtable

MAEtable = cbind(as.numeric(FebruaryTable[,4]),as.numeric(JulyTable[,4]),as.numeric(SeptemberTable[,4]),as.numeric(DecemberTable[,4]))
rownames(MAEtable) = c("Point","7 days","14 days","21 days","28 days")
colnames(MAEtable) = c("February","July","September","December")
AverageMAEtable = rowMeans(MAEtable)
AverageMAEtable

MASEtable = cbind(as.numeric(FebruaryTable[,7]),as.numeric(JulyTable[,7]),as.numeric(SeptemberTable[,7]),as.numeric(DecemberTable[,7]))
rownames(MASEtable) = c("Point","7 days","14 days","21 days","28 days")
colnames(MASEtable) = c("February","July","September","December")
AverageMASEtable = rowMeans(MASEtable)
AverageMASEtable

prettyplot1
prettyplot2
prettyplot3
prettyplot4
```
#######################
## Robustness chekcs ##
#######################

##########
## 2019 ##
##########
```{r}
library(forecast)
library(readxl)
EnergyDataset <- read_excel("/Users/nicklasschmidt/Downloads/Master thesis/Dataset/EnergyDataset.xlsx", 
    col_types = c("date", "numeric", "numeric", 
        "numeric", "numeric", "numeric", 
        "numeric"))
# 
StartYear = 2017
Year = 2019
Month = c("January", "March", "August", "November")
MonthNumber = c(1, 59, 214, 305)

for(MonthVariables in 1:4){
naivedata=subset(EnergyDataset[1:2623,1:2])
# First we convert dataset into a time series object
naivedec = ts(EnergyDataset[,2:2], start = c(2015,1), frequency = 365 )

#Subsetting train and test data using window()function 
month2019train = window(naivedec, start = c(startYear, MonthNumber[MonthVariables]), end = c(Year, MonthNumber[MonthVariables]))
month2019test = window(naivedec, start = c(Year, MonthNumber[MonthVariables]))

#Models estimating the best pdq.
arima2019=Arima(month2019train, order = c(7, 1, 2))

#Forecasting for 1-28 days 
model1dec2019=forecast(arima2019,h=1, level=c(99.5))
model7dec2019=forecast(arima2019,h=7, level=c(99.5))
model14dec2019=forecast(arima2019,h=14, level=c(99.5))
model21dec2019=forecast(arima2019,h=21, level=c(99.5))
model28dec2019=forecast(arima2019,h=28, level=c(99.5))

# Accuracy TABLE
decna1=forecast::accuracy(model1dec2019, month2019test, d=1, D=0)[2,1:6]
decna7=forecast::accuracy(model7dec2019, month2019test, d=1, D=0)[2,1:6]
decna14=forecast::accuracy(model14dec2019, month2019test, d=1, D=0)[2,1:6]
decna21=forecast::accuracy(model21dec2019, month2019test, d=1, D=0)[2,1:6]
decna28=forecast::accuracy(model28dec2019, month2019test, d=1, D=0)[2,1:6]

accuracytable = rbind(decna1,decna7,decna14,decna21,decna28)
#plot table
naivetable = cbind(Month[MonthVariables],accuracytable)
rownames(naivetable) = c("Point","7 days","14 days","21 days","28 days")

if (MonthVariables == 1) {FebruaryTable = naivetable}
if (MonthVariables == 2) {JulyTable = naivetable}
if (MonthVariables == 3) {SeptemberTable = naivetable}
if (MonthVariables == 4) {DecemberTable = naivetable}
}
#subset DK1 
FebruaryTable[,c(3,4,7)]
JulyTable[,c(3,4,7)]
SeptemberTable[,c(3,4,7)]
DecemberTable[,c(3,4,7)]

RMSEtable = cbind(as.numeric(FebruaryTable[,3]),as.numeric(JulyTable[,3]),as.numeric(SeptemberTable[,3]),as.numeric(DecemberTable[,3]))
rownames(RMSEtable) = c("Point","7 days","14 days","21 days","28 days")
colnames(RMSEtable) = c("February","July","September","December")
AverageRMSEtable = rowMeans(RMSEtable)
AverageRMSEtable

MAEtable = cbind(as.numeric(FebruaryTable[,4]),as.numeric(JulyTable[,4]),as.numeric(SeptemberTable[,4]),as.numeric(DecemberTable[,4]))
rownames(MAEtable) = c("Point","7 days","14 days","21 days","28 days")
colnames(MAEtable) = c("February","July","September","December")
AverageMAEtable = rowMeans(MAEtable)
AverageMAEtable

MASEtable = cbind(as.numeric(FebruaryTable[,7]),as.numeric(JulyTable[,7]),as.numeric(SeptemberTable[,7]),as.numeric(DecemberTable[,7]))
rownames(MASEtable) = c("Point","7 days","14 days","21 days","28 days")
colnames(MASEtable) = c("February","July","September","December")
AverageMASEtable = rowMeans(MASEtable)
AverageMASEtable
```
##########
## 2021 ##
##########
```{r}
library(forecast)
library(readxl)
EnergyDataset <- read_excel("/Users/nicklasschmidt/Downloads/Master thesis/Dataset/EnergyDataset.xlsx", 
    col_types = c("date", "numeric", "numeric", 
        "numeric", "numeric", "numeric", 
        "numeric"))
# 
startYear = 2019
Year = 2021
Month = c("January", "March", "August", "November")
MonthNumber = c(1, 59, 214, 305)

for(MonthVariables in 1:4){
naivedata=subset(EnergyDataset[1:2623,1:2])
# First we convert dataset into a time series object
naivedec = ts(EnergyDataset[,2:2], start = c(2015,1), frequency = 365 )

#Subsetting train and test data using window()function 
month2019train = window(naivedec, start = c(startYear, MonthNumber[MonthVariables]), end = c(Year, MonthNumber[MonthVariables]))
month2019test = window(naivedec, start = c(Year, MonthNumber[MonthVariables]))

#Models estimating the best pdq.
arima2019=Arima(month2019train, order = c(7, 1, 2))

#Forecasting for 1-28 days 
model1dec2019=forecast(arima2019,h=1, level=c(99.5))
model7dec2019=forecast(arima2019,h=7, level=c(99.5))
model14dec2019=forecast(arima2019,h=14, level=c(99.5))
model21dec2019=forecast(arima2019,h=21, level=c(99.5))
model28dec2019=forecast(arima2019,h=28, level=c(99.5))

# Accuracy TABLE
decna1=forecast::accuracy(model1dec2019, month2019test, d=1, D=0)[2,1:6]
decna7=forecast::accuracy(model7dec2019, month2019test, d=1, D=0)[2,1:6]
decna14=forecast::accuracy(model14dec2019, month2019test, d=1, D=0)[2,1:6]
decna21=forecast::accuracy(model21dec2019, month2019test, d=1, D=0)[2,1:6]
decna28=forecast::accuracy(model28dec2019, month2019test, d=1, D=0)[2,1:6]

accuracytable = rbind(decna1,decna7,decna14,decna21,decna28)
#plot table
naivetable = cbind(Month[MonthVariables],accuracytable)
rownames(naivetable) = c("Point","7 days","14 days","21 days","28 days")

if (MonthVariables == 1) {FebruaryTable = naivetable}
if (MonthVariables == 2) {JulyTable = naivetable}
if (MonthVariables == 3) {SeptemberTable = naivetable}
if (MonthVariables == 4) {DecemberTable = naivetable}
}
#subset DK1 
FebruaryTable[,c(3,4,7)]
JulyTable[,c(3,4,7)]
SeptemberTable[,c(3,4,7)]
DecemberTable[,c(3,4,7)]

RMSEtable = cbind(as.numeric(FebruaryTable[,3]),as.numeric(JulyTable[,3]),as.numeric(SeptemberTable[,3]),as.numeric(DecemberTable[,3]))
rownames(RMSEtable) = c("Point","7 days","14 days","21 days","28 days")
colnames(RMSEtable) = c("February","July","September","December")
AverageRMSEtable = rowMeans(RMSEtable)
AverageRMSEtable

MAEtable = cbind(as.numeric(FebruaryTable[,4]),as.numeric(JulyTable[,4]),as.numeric(SeptemberTable[,4]),as.numeric(DecemberTable[,4]))
rownames(MAEtable) = c("Point","7 days","14 days","21 days","28 days")
colnames(MAEtable) = c("February","July","September","December")
AverageMAEtable = rowMeans(MAEtable)
AverageMAEtable

MASEtable = cbind(as.numeric(FebruaryTable[,7]),as.numeric(JulyTable[,7]),as.numeric(SeptemberTable[,7]),as.numeric(DecemberTable[,7]))
rownames(MASEtable) = c("Point","7 days","14 days","21 days","28 days")
colnames(MASEtable) = c("February","July","September","December")
AverageMASEtable = rowMeans(MASEtable)
AverageMASEtable
```






#############################
## Heterogeneity testing   ##
#############################

##########
## 2019 ##
##########
```{r}
library(forecast)
library(readxl)
EnergyDataset <- read_excel("/Users/nicklasschmidt/Downloads/Master thesis/Dataset/EnergyDataset.xlsx", 
    col_types = c("date", "numeric", "numeric", 
        "numeric", "numeric", "numeric", 
        "numeric"))
# 
startYear = 2017
Year = 2019
Month = c("February", "July", "September", "December")
MonthNumber = c(32, 182, 244, 335)

for(MonthVariables in 1:4){
naivedata=subset(EnergyDataset[1:2623,1:2])
# First we convert dataset into a time series object
naivedec = ts(EnergyDataset[,3:3], start = c(2015,1), frequency = 365 )

#Subsetting train and test data using window()function 
month2019train = window(naivedec, start = c(startYear, MonthNumber[MonthVariables]), end = c(Year, MonthNumber[MonthVariables]))
month2019test = window(naivedec, start = c(Year, MonthNumber[MonthVariables]))

#Models estimating the best pdq.
arima2019=Arima(month2019train, order = c(7, 1, 2))

#Forecasting for 1-28 days 
model1dec2019=forecast(arima2019,h=1, level=c(99.5))
model7dec2019=forecast(arima2019,h=7, level=c(99.5))
model14dec2019=forecast(arima2019,h=14, level=c(99.5))
model21dec2019=forecast(arima2019,h=21, level=c(99.5))
model28dec2019=forecast(arima2019,h=28, level=c(99.5))

# Accuracy TABLE
decna1=forecast::accuracy(model1dec2019, month2019test, d=1, D=0)[2,1:6]
decna7=forecast::accuracy(model7dec2019, month2019test, d=1, D=0)[2,1:6]
decna14=forecast::accuracy(model14dec2019, month2019test, d=1, D=0)[2,1:6]
decna21=forecast::accuracy(model21dec2019, month2019test, d=1, D=0)[2,1:6]
decna28=forecast::accuracy(model28dec2019, month2019test, d=1, D=0)[2,1:6]
accuracytable = rbind(decna1,decna7,decna14,decna21,decna28)
#plot table
naivetable = cbind(Month[MonthVariables],accuracytable)
rownames(naivetable) = c("Point","7 days","14 days","21 days","28 days")

if (MonthVariables == 1) {FebruaryTable = naivetable}
if (MonthVariables == 2) {JulyTable = naivetable}
if (MonthVariables == 3) {SeptemberTable = naivetable}
if (MonthVariables == 4) {DecemberTable = naivetable}
}
#subset DK1 
FebruaryTable[,c(3,4,7)]
JulyTable[,c(3,4,7)]
SeptemberTable[,c(3,4,7)]
DecemberTable[,c(3,4,7)]

RMSEtable = cbind(as.numeric(FebruaryTable[,3]),as.numeric(JulyTable[,3]),as.numeric(SeptemberTable[,3]),as.numeric(DecemberTable[,3]))
rownames(RMSEtable) = c("Point","7 days","14 days","21 days","28 days")
colnames(RMSEtable) = c("February","July","September","December")
AverageRMSEtable = rowMeans(RMSEtable)
AverageRMSEtable

MAEtable = cbind(as.numeric(FebruaryTable[,4]),as.numeric(JulyTable[,4]),as.numeric(SeptemberTable[,4]),as.numeric(DecemberTable[,4]))
rownames(MAEtable) = c("Point","7 days","14 days","21 days","28 days")
colnames(MAEtable) = c("February","July","September","December")
AverageMAEtable = rowMeans(MAEtable)
AverageMAEtable

MASEtable = cbind(as.numeric(FebruaryTable[,7]),as.numeric(JulyTable[,7]),as.numeric(SeptemberTable[,7]),as.numeric(DecemberTable[,7]))
rownames(MASEtable) = c("Point","7 days","14 days","21 days","28 days")
colnames(MASEtable) = c("February","July","September","December")
AverageMASEtable = rowMeans(MASEtable)
AverageMASEtable
```

##########
## 2021 ##
##########
```{r}
library(forecast)
library(readxl)
EnergyDataset <- read_excel("/Users/nicklasschmidt/Downloads/Master thesis/Dataset/EnergyDataset.xlsx", 
    col_types = c("date", "numeric", "numeric", 
        "numeric", "numeric", "numeric", 
        "numeric"))
# 
startyear = 2019
Year = 2021
Month = c("February", "July", "September", "December")
MonthNumber = c(32, 182, 244, 335)

for(MonthVariables in 1:4){
naivedata=subset(EnergyDataset[1:2623,1:2])
# First we convert dataset into a time series object
naivedec = ts(EnergyDataset[,3:3], start = c(2015,1), frequency = 365 )

#Subsetting train and test data using window()function 
month2019train = window(naivedec, start = c(startYear, MonthNumber[MonthVariables]), end = c(Year, MonthNumber[MonthVariables]))
month2019test = window(naivedec, start = c(Year, MonthNumber[MonthVariables]))

#Models estimating the best pdq.
arima2019=Arima(month2019train, order = c(7, 1, 2))

#Forecasting for 1-28 days 
model1dec2019=forecast(arima2019,h=1, level=c(99.5))
model7dec2019=forecast(arima2019,h=7, level=c(99.5))
model14dec2019=forecast(arima2019,h=14, level=c(99.5))
model21dec2019=forecast(arima2019,h=21, level=c(99.5))
model28dec2019=forecast(arima2019,h=28, level=c(99.5))

# Accuracy TABLE
decna1=forecast::accuracy(model1dec2019, month2019test, d=1, D=0)[2,1:6]
decna7=forecast::accuracy(model7dec2019, month2019test, d=1, D=0)[2,1:6]
decna14=forecast::accuracy(model14dec2019, month2019test, d=1, D=0)[2,1:6]
decna21=forecast::accuracy(model21dec2019, month2019test, d=1, D=0)[2,1:6]
decna28=forecast::accuracy(model28dec2019, month2019test, d=1, D=0)[2,1:6]

accuracytable = rbind(decna1,decna7,decna14,decna21,decna28)
#plot table
naivetable = cbind(Month[MonthVariables],accuracytable)
rownames(naivetable) = c("Point","7 days","14 days","21 days","28 days")

if (MonthVariables == 1) {FebruaryTable = naivetable}
if (MonthVariables == 2) {JulyTable = naivetable}
if (MonthVariables == 3) {SeptemberTable = naivetable}
if (MonthVariables == 4) {DecemberTable = naivetable}
}
#subset DK1 
FebruaryTable[,c(3,4,7)]
JulyTable[,c(3,4,7)]
SeptemberTable[,c(3,4,7)]
DecemberTable[,c(3,4,7)]

RMSEtable = cbind(as.numeric(FebruaryTable[,3]),as.numeric(JulyTable[,3]),as.numeric(SeptemberTable[,3]),as.numeric(DecemberTable[,3]))
rownames(RMSEtable) = c("Point","7 days","14 days","21 days","28 days")
colnames(RMSEtable) = c("February","July","September","December")
AverageRMSEtable = rowMeans(RMSEtable)
AverageRMSEtable

MAEtable = cbind(as.numeric(FebruaryTable[,4]),as.numeric(JulyTable[,4]),as.numeric(SeptemberTable[,4]),as.numeric(DecemberTable[,4]))
rownames(MAEtable) = c("Point","7 days","14 days","21 days","28 days")
colnames(MAEtable) = c("February","July","September","December")
AverageMAEtable = rowMeans(MAEtable)
AverageMAEtable

MASEtable = cbind(as.numeric(FebruaryTable[,7]),as.numeric(JulyTable[,7]),as.numeric(SeptemberTable[,7]),as.numeric(DecemberTable[,7]))
rownames(MASEtable) = c("Point","7 days","14 days","21 days","28 days")
colnames(MASEtable) = c("February","July","September","December")
AverageMASEtable = rowMeans(MASEtable)
AverageMASEtable
```

############################
## 2019 all months SARIMA ##
############################
```{r}
library(forecast)
library(readxl)
EnergyDataset <- read_excel("/Users/nicklasschmidt/Downloads/Master thesis/Dataset/EnergyDataset.xlsx", 
    col_types = c("date", "numeric", "numeric", 
        "numeric", "numeric", "numeric", 
        "numeric"))

startYear = 2017
Year = 2019
Month = c("February", "July", "September", "December")
MonthNumber = c(32, 182, 244, 335)

for(MonthVariables in 1:4){
naivedata=subset(EnergyDataset[1:2623,1:2])
# First we convert dataset into a time series object
naivedec = ts(EnergyDataset[,2:2], start = c(2015,1), frequency = 365 )

#Subsetting train and test data using window()function 
month2019train = window(naivedec, start = c(startYear, MonthNumber[MonthVariables]), end = c(Year, MonthNumber[MonthVariables]))
month2019test = window(naivedec, start = c(Year, MonthNumber[MonthVariables]))

#Models estimating the best pdq.
#arima2019=auto.arima(month2019train, trace=TRUE, approximation = T,allowdrift = T,allowmean = T) 
arima2019=Arima(month2019train, order = c(7, 1, 2), seasonal = list(order=c(0,1,0)))

#Forecasting for 1-28 days 
model1dec2019=forecast(arima2019,h=1, level=c(95))
model7dec2019=forecast(arima2019,h=7, level=c(95))
model14dec2019=forecast(arima2019,h=14, level=c(95))
model21dec2019=forecast(arima2019,h=21, level=c(95))
model28dec2019=forecast(arima2019,h=28, level=c(95))

# Accuracy TABLE
decna1=forecast::accuracy(model1dec2019, month2019test, d=1, D=0)[2,1:6]
decna7=forecast::accuracy(model7dec2019, month2019test, d=1, D=0)[2,1:6]
decna14=forecast::accuracy(model14dec2019, month2019test, d=1, D=0)[2,1:6]
decna21=forecast::accuracy(model21dec2019, month2019test, d=1, D=0)[2,1:6]
decna28=forecast::accuracy(model28dec2019, month2019test, d=1, D=0)[2,1:6]

accuracytable = rbind(decna1,decna7,decna14,decna21,decna28)
#plot table
naivetable = cbind(Month[MonthVariables],accuracytable)
rownames(naivetable) = c("Point","7 days","14 days","21 days","28 days")

naivetsplot = window(naivedec, start = c(Year, 1),end = c(Year + 1,1))
prettyplot = autoplot(naivetsplot, xlab = "Year", ylab = "Electricity price in DK1 area", main="Vector AR plot, h=1,7,14,21,28")+autolayer(model28dec2019, series = "28 Days", PI = FALSE, size = 1)+autolayer(model21dec2019, series = "21 Days", PI = FALSE, size = 1)+autolayer(model14dec2019, series = "14 Days", PI = FALSE, size = 1)+autolayer(model7dec2019, series = "7 Days", PI = FALSE, size = 1)+autolayer(model1dec2019, series = "Days point", PI = FALSE, size = 1)
assign(paste0("prettyplot",MonthVariables),prettyplot)

if (MonthVariables == 1) {FebruaryTable = naivetable}
if (MonthVariables == 2) {JulyTable = naivetable}
if (MonthVariables == 3) {SeptemberTable = naivetable}
if (MonthVariables == 4) {DecemberTable = naivetable}
}
#subset DK1 
FebruaryTable[,c(3,4,7)]
JulyTable[,c(3,4,7)]
SeptemberTable[,c(3,4,7)]
DecemberTable[,c(3,4,7)]

RMSEtable = cbind(as.numeric(FebruaryTable[,3]),as.numeric(JulyTable[,3]),as.numeric(SeptemberTable[,3]),as.numeric(DecemberTable[,3]))
rownames(RMSEtable) = c("Point","7 days","14 days","21 days","28 days")
colnames(RMSEtable) = c("February","July","September","December")
AverageRMSEtable = rowMeans(RMSEtable)
AverageRMSEtable

MAEtable = cbind(as.numeric(FebruaryTable[,4]),as.numeric(JulyTable[,4]),as.numeric(SeptemberTable[,4]),as.numeric(DecemberTable[,4]))
rownames(MAEtable) = c("Point","7 days","14 days","21 days","28 days")
colnames(MAEtable) = c("February","July","September","December")
AverageMAEtable = rowMeans(MAEtable)
AverageMAEtable

MASEtable = cbind(as.numeric(FebruaryTable[,7]),as.numeric(JulyTable[,7]),as.numeric(SeptemberTable[,7]),as.numeric(DecemberTable[,7]))
rownames(MASEtable) = c("Point","7 days","14 days","21 days","28 days")
colnames(MASEtable) = c("February","July","September","December")
AverageMASEtable = rowMeans(MASEtable)
AverageMASEtable

prettyplot1
prettyplot2
prettyplot3
prettyplot4
```

############################
## 2021 all months SARIMA ##
############################
```{r}
library(forecast)
library(readxl)
EnergyDataset <- read_excel("/Users/nicklasschmidt/Downloads/Master thesis/Dataset/EnergyDataset.xlsx", 
    col_types = c("date", "numeric", "numeric", 
        "numeric", "numeric", "numeric", 
        "numeric"))

startYear = 2019
Year = 2021
Month = c("February", "July", "September", "December")
MonthNumber = c(32, 182, 244, 335)

for(MonthVariables in 1:4){
naivedata=subset(EnergyDataset[1:2623,1:2])
# First we convert dataset into a time series object
naivedec = ts(EnergyDataset[,2:2], start = c(2015,1), frequency = 365 )

#Subsetting train and test data using window()function 
month2019train = window(naivedec, start = c(startYear, MonthNumber[MonthVariables]), end = c(Year, MonthNumber[MonthVariables]))
month2019test = window(naivedec, start = c(Year, MonthNumber[MonthVariables]))

#Models estimating the best pdq.
#arima2019=auto.arima(month2019train, trace=TRUE, approximation = T,allowdrift = T,allowmean = T) 
arima2019=Arima(month2019train, order = c(7, 1, 2), seasonal = list(order=c(0,1,0)))

#Forecasting for 1-28 days 
model1dec2019=forecast(arima2019,h=1, level=c(95))
model7dec2019=forecast(arima2019,h=7, level=c(95))
model14dec2019=forecast(arima2019,h=14, level=c(95))
model21dec2019=forecast(arima2019,h=21, level=c(95))
model28dec2019=forecast(arima2019,h=28, level=c(95))

# Accuracy TABLE
decna1=forecast::accuracy(model1dec2019, month2019test, d=1, D=0)[2,1:6]
decna7=forecast::accuracy(model7dec2019, month2019test, d=1, D=0)[2,1:6]
decna14=forecast::accuracy(model14dec2019, month2019test, d=1, D=0)[2,1:6]
decna21=forecast::accuracy(model21dec2019, month2019test, d=1, D=0)[2,1:6]
decna28=forecast::accuracy(model28dec2019, month2019test, d=1, D=0)[2,1:6]

accuracytable = rbind(decna1,decna7,decna14,decna21,decna28)
#plot table
naivetable = cbind(Month[MonthVariables],accuracytable)
rownames(naivetable) = c("Point","7 days","14 days","21 days","28 days")

naivetsplot = window(naivedec, start = c(Year, 1),end = c(Year + 1,1))
prettyplot = autoplot(naivetsplot, xlab = "Year", ylab = "Electricity price in DK1 area", main="Vector AR plot, h=1,7,14,21,28")+autolayer(model28dec2019, series = "28 Days", PI = FALSE, size = 1)+autolayer(model21dec2019, series = "21 Days", PI = FALSE, size = 1)+autolayer(model14dec2019, series = "14 Days", PI = FALSE, size = 1)+autolayer(model7dec2019, series = "7 Days", PI = FALSE, size = 1)+autolayer(model1dec2019, series = "Days point", PI = FALSE, size = 1)
assign(paste0("prettyplot",MonthVariables),prettyplot)

if (MonthVariables == 1) {FebruaryTable = naivetable}
if (MonthVariables == 2) {JulyTable = naivetable}
if (MonthVariables == 3) {SeptemberTable = naivetable}
if (MonthVariables == 4) {DecemberTable = naivetable}
}
#subset DK1 
FebruaryTable[,c(3,4,7)]
JulyTable[,c(3,4,7)]
SeptemberTable[,c(3,4,7)]
DecemberTable[,c(3,4,7)]

RMSEtable = cbind(as.numeric(FebruaryTable[,3]),as.numeric(JulyTable[,3]),as.numeric(SeptemberTable[,3]),as.numeric(DecemberTable[,3]))
rownames(RMSEtable) = c("Point","7 days","14 days","21 days","28 days")
colnames(RMSEtable) = c("February","July","September","December")
AverageRMSEtable = rowMeans(RMSEtable)
AverageRMSEtable

MAEtable = cbind(as.numeric(FebruaryTable[,4]),as.numeric(JulyTable[,4]),as.numeric(SeptemberTable[,4]),as.numeric(DecemberTable[,4]))
rownames(MAEtable) = c("Point","7 days","14 days","21 days","28 days")
colnames(MAEtable) = c("February","July","September","December")
AverageMAEtable = rowMeans(MAEtable)
AverageMAEtable

MASEtable = cbind(as.numeric(FebruaryTable[,7]),as.numeric(JulyTable[,7]),as.numeric(SeptemberTable[,7]),as.numeric(DecemberTable[,7]))
rownames(MASEtable) = c("Point","7 days","14 days","21 days","28 days")
colnames(MASEtable) = c("February","July","September","December")
AverageMASEtable = rowMeans(MASEtable)
AverageMASEtable

prettyplot1
prettyplot2
prettyplot3
prettyplot4
```
